# Используем официальный образ PostgreSQL
FROM postgres:14
RUN apt-get update && apt-get install -y postgresql-14-cron

# Копируем SQL-файл для создания таблиц
COPY sql/0-create_tables.sql /docker-entrypoint-initdb.d/

# Указываем переменные окружения для настройки PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=123
ENV POSTGRES_DB=medscheduler