# Используем официальный образ PostgreSQL
FROM postgres:13

# Копируем SQL-файл для создания таблиц
COPY create_tables.sql /docker-entrypoint-initdb.d/

# Указываем переменные окружения для настройки PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=123
ENV POSTGRES_DB=medscheduler