name: CI

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deployFront.tar ../build/

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          port: 22
          source: "deployFront.tar"
          target: "/root/"

      - name: Run Docker CMD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          port: 22
          script: |
            rm -rf /root/vipawn-frontend
            mkdir /root/vipawn-frontend
            cd /root/vipawn-frontend
            tar -xvf ../deployFront.tar
            cd /root/vipawn-frontend/build
            docker build . --tag vipawn-frontend:latest
            docker stop vipawn-frontend || true  && docker rm vipawn-frontend || true
            docker run -p 127.0.0.1:3090:3000 -d --name=vipawn-frontend --restart unless-stopped vipawn-frontend:latest